### PR TITLE
PR: Release latest version of package with all dependencies updated #116

### PR DESCRIPTION
**Pull request by nelsonic**
This PR publishes a new version of the `fields` package to Hex.pm so that the latest version of the crypto is used in the downstream packages #116 hoping to fix https://github.com/dwyl/auth/pull/231/#issuecomment-1282165231 ... 🤞 

+ [x] Update crypto cipher from `:aes_256_gcm` with `:aes_gcm` 
  see: #118

### CODE REVIEW

**Comment by nelsonic** [comment]
Sorry for all the random updates in the `README.md` ... VSCodium ... 🙄

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/fields/2.10.0 📦 🚀

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/fields/2.10.1 📦 🤞 
Testing now in `auth` ... https://github.com/dwyl/auth/pull/231/

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/fields/2.10.2 📦 (3<sup>rd</sup> time lucky ...) 🍀 
Testing in **`auth`** ... https://github.com/dwyl/auth/pull/231 ⏳

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/fields/2.10.3 📦  ... OK this is getting a bit ridiculous!
Buuuuuuttt ... https://github.com/dwyl/auth/pull/231#issuecomment-1282534860 🤦‍♂️

**Review by SimonLab — APPROVED** [review]
Looks good, thanks :+1:

**Pull request merged**
